import { CounterItem } from "../../../models/global";
import createGenericSlice from "../genericSlice";

// Create a slice for 'counter' using the generic slice creator
const counterSlice = createGenericSlice<CounterItem>('counter');

// Export actions generated by the slice
export const {
  createItem: createCounter,
  readItems: readCounters,
  updateItem: updateCounter,
  deleteItem: deleteCounter,
  selectItem: selectCounter,
  clearSelection: clearCounterSelection,
} = counterSlice.actions;

// Export the reducer for the slice to be added to the store
export default counterSlice.reducer;