import { User } from "../../../models/global";
import createGenericSlice from "../genericSlice";

// Create a slice for 'user' using the generic slice utility
const userSlice = createGenericSlice<User>("user");

// Export actions generated by the slice for easy use in components
export const {
  createItem: createUser,
  readItems: readUsers,
  updateItem: updateUser,
  deleteItem: deleteUser,
  selectItem: selectUser,
  clearSelection: clearUserSelection,
} = userSlice.actions;

// Export the reducer for the user slice to be added to the store
export default userSlice.reducer;